version: "3"

includes:
  gke:
    taskfile: ./kubernetes/Taskfile-gke.yml
    dir: ./kubernetes/
  
  dev:
    taskfile: ./kubernetes/.development/Taskfile-dev.yml
    dir: ./kubernetes/.development
