// Code generated by MockGen. DO NOT EDIT.
// Source: internal/controller/manifestrequesttemplate_controller.go
//
// Generated by this command:
//
//	mockgen -source=internal/controller/manifestrequesttemplate_controller.go -destination=internal/controller/mocks/manifestrequesttemplate_controller_mock.go -package=controller_mock
//

// Package controller_mock is a generated GoMock package.
package controller_mock

import (
	context "context"
	reflect "reflect"

	v1alpha1 "github.com/AlwaysSayNo/quorum-based-manifests-governance/kubernetes/api/v1alpha1"
	repository "github.com/AlwaysSayNo/quorum-based-manifests-governance/kubernetes/internal/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockRepositoryManager is a mock of RepositoryManager interface.
type MockRepositoryManager struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryManagerMockRecorder
	isgomock struct{}
}

// MockRepositoryManagerMockRecorder is the mock recorder for MockRepositoryManager.
type MockRepositoryManagerMockRecorder struct {
	mock *MockRepositoryManager
}

// NewMockRepositoryManager creates a new mock instance.
func NewMockRepositoryManager(ctrl *gomock.Controller) *MockRepositoryManager {
	mock := &MockRepositoryManager{ctrl: ctrl}
	mock.recorder = &MockRepositoryManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepositoryManager) EXPECT() *MockRepositoryManagerMockRecorder {
	return m.recorder
}

// GetProviderForMRT mocks base method.
func (m *MockRepositoryManager) GetProviderForMRT(ctx context.Context, mrt *v1alpha1.ManifestRequestTemplate) (repository.GitRepository, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProviderForMRT", ctx, mrt)
	ret0, _ := ret[0].(repository.GitRepository)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProviderForMRT indicates an expected call of GetProviderForMRT.
func (mr *MockRepositoryManagerMockRecorder) GetProviderForMRT(ctx, mrt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProviderForMRT", reflect.TypeOf((*MockRepositoryManager)(nil).GetProviderForMRT), ctx, mrt)
}

// MockNotifier is a mock of Notifier interface.
type MockNotifier struct {
	ctrl     *gomock.Controller
	recorder *MockNotifierMockRecorder
	isgomock struct{}
}

// MockNotifierMockRecorder is the mock recorder for MockNotifier.
type MockNotifierMockRecorder struct {
	mock *MockNotifier
}

// NewMockNotifier creates a new mock instance.
func NewMockNotifier(ctrl *gomock.Controller) *MockNotifier {
	mock := &MockNotifier{ctrl: ctrl}
	mock.recorder = &MockNotifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotifier) EXPECT() *MockNotifierMockRecorder {
	return m.recorder
}

// NotifyGovernors mocks base method.
func (m *MockNotifier) NotifyGovernors(ctx context.Context, mrt *v1alpha1.ManifestRequestTemplate, msr *v1alpha1.ManifestSigningRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NotifyGovernors", ctx, mrt, msr)
	ret0, _ := ret[0].(error)
	return ret0
}

// NotifyGovernors indicates an expected call of NotifyGovernors.
func (mr *MockNotifierMockRecorder) NotifyGovernors(ctx, mrt, msr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyGovernors", reflect.TypeOf((*MockNotifier)(nil).NotifyGovernors), ctx, mrt, msr)
}
