// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/manager.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/manager.go -destination=internal/repository/mocks/manager_mock.go -package=manager_mock
//

// Package manager_mock is a generated GoMock package.
package manager_mock

import (
	context "context"
	reflect "reflect"

	v1alpha1 "github.com/AlwaysSayNo/quorum-based-manifests-governance/kubernetes/api/v1alpha1"
	repository "github.com/AlwaysSayNo/quorum-based-manifests-governance/kubernetes/internal/repository"
	dto "github.com/AlwaysSayNo/quorum-based-manifests-governance/pkg/api/dto"
	transport "github.com/go-git/go-git/v5/plumbing/transport"
	gomock "go.uber.org/mock/gomock"
)

// MockGitRepositoryFactory is a mock of GitRepositoryFactory interface.
type MockGitRepositoryFactory struct {
	ctrl     *gomock.Controller
	recorder *MockGitRepositoryFactoryMockRecorder
	isgomock struct{}
}

// MockGitRepositoryFactoryMockRecorder is the mock recorder for MockGitRepositoryFactory.
type MockGitRepositoryFactoryMockRecorder struct {
	mock *MockGitRepositoryFactory
}

// NewMockGitRepositoryFactory creates a new mock instance.
func NewMockGitRepositoryFactory(ctrl *gomock.Controller) *MockGitRepositoryFactory {
	mock := &MockGitRepositoryFactory{ctrl: ctrl}
	mock.recorder = &MockGitRepositoryFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGitRepositoryFactory) EXPECT() *MockGitRepositoryFactoryMockRecorder {
	return m.recorder
}

// IdentifyProvider mocks base method.
func (m *MockGitRepositoryFactory) IdentifyProvider(repoURL string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IdentifyProvider", repoURL)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IdentifyProvider indicates an expected call of IdentifyProvider.
func (mr *MockGitRepositoryFactoryMockRecorder) IdentifyProvider(repoURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IdentifyProvider", reflect.TypeOf((*MockGitRepositoryFactory)(nil).IdentifyProvider), repoURL)
}

// New mocks base method.
func (m *MockGitRepositoryFactory) New(ctx context.Context, remoteURL, localPath string, auth transport.AuthMethod, pgpSecrets repository.PgpSecrets) (repository.GitRepository, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "New", ctx, remoteURL, localPath, auth, pgpSecrets)
	ret0, _ := ret[0].(repository.GitRepository)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// New indicates an expected call of New.
func (mr *MockGitRepositoryFactoryMockRecorder) New(ctx, remoteURL, localPath, auth, pgpSecrets any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "New", reflect.TypeOf((*MockGitRepositoryFactory)(nil).New), ctx, remoteURL, localPath, auth, pgpSecrets)
}

// MockGitRepository is a mock of GitRepository interface.
type MockGitRepository struct {
	ctrl     *gomock.Controller
	recorder *MockGitRepositoryMockRecorder
	isgomock struct{}
}

// MockGitRepositoryMockRecorder is the mock recorder for MockGitRepository.
type MockGitRepositoryMockRecorder struct {
	mock *MockGitRepository
}

// NewMockGitRepository creates a new mock instance.
func NewMockGitRepository(ctrl *gomock.Controller) *MockGitRepository {
	mock := &MockGitRepository{ctrl: ctrl}
	mock.recorder = &MockGitRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGitRepository) EXPECT() *MockGitRepositoryMockRecorder {
	return m.recorder
}

// FetchMSRByVersion mocks base method.
func (m *MockGitRepository) FetchMSRByVersion(ctx context.Context, msr *v1alpha1.ManifestSigningRequest) (*dto.ManifestSigningRequestManifestObject, []byte, dto.SignatureData, []dto.SignatureData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchMSRByVersion", ctx, msr)
	ret0, _ := ret[0].(*dto.ManifestSigningRequestManifestObject)
	ret1, _ := ret[1].([]byte)
	ret2, _ := ret[2].(dto.SignatureData)
	ret3, _ := ret[3].([]dto.SignatureData)
	ret4, _ := ret[4].(error)
	return ret0, ret1, ret2, ret3, ret4
}

// FetchMSRByVersion indicates an expected call of FetchMSRByVersion.
func (mr *MockGitRepositoryMockRecorder) FetchMSRByVersion(ctx, msr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchMSRByVersion", reflect.TypeOf((*MockGitRepository)(nil).FetchMSRByVersion), ctx, msr)
}

// GetChangedFiles mocks base method.
func (m *MockGitRepository) GetChangedFiles(ctx context.Context, fromCommit, toCommit, fromFolder string) ([]v1alpha1.FileChange, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChangedFiles", ctx, fromCommit, toCommit, fromFolder)
	ret0, _ := ret[0].([]v1alpha1.FileChange)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChangedFiles indicates an expected call of GetChangedFiles.
func (mr *MockGitRepositoryMockRecorder) GetChangedFiles(ctx, fromCommit, toCommit, fromFolder any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChangedFiles", reflect.TypeOf((*MockGitRepository)(nil).GetChangedFiles), ctx, fromCommit, toCommit, fromFolder)
}

// GetLatestRevision mocks base method.
func (m *MockGitRepository) GetLatestRevision(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestRevision", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestRevision indicates an expected call of GetLatestRevision.
func (mr *MockGitRepositoryMockRecorder) GetLatestRevision(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestRevision", reflect.TypeOf((*MockGitRepository)(nil).GetLatestRevision), ctx)
}

// HasRevision mocks base method.
func (m *MockGitRepository) HasRevision(ctx context.Context, commit string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasRevision", ctx, commit)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasRevision indicates an expected call of HasRevision.
func (mr *MockGitRepositoryMockRecorder) HasRevision(ctx, commit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasRevision", reflect.TypeOf((*MockGitRepository)(nil).HasRevision), ctx, commit)
}

// InitializeGovernance mocks base method.
func (m *MockGitRepository) InitializeGovernance(ctx context.Context, operationalFileLocation, governanceIndexAlias string, mrt *v1alpha1.ManifestRequestTemplate) (string, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitializeGovernance", ctx, operationalFileLocation, governanceIndexAlias, mrt)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// InitializeGovernance indicates an expected call of InitializeGovernance.
func (mr *MockGitRepositoryMockRecorder) InitializeGovernance(ctx, operationalFileLocation, governanceIndexAlias, mrt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitializeGovernance", reflect.TypeOf((*MockGitRepository)(nil).InitializeGovernance), ctx, operationalFileLocation, governanceIndexAlias, mrt)
}

// IsNotAfter mocks base method.
func (m *MockGitRepository) IsNotAfter(ctx context.Context, ancestor, child string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsNotAfter", ctx, ancestor, child)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsNotAfter indicates an expected call of IsNotAfter.
func (mr *MockGitRepositoryMockRecorder) IsNotAfter(ctx, ancestor, child any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsNotAfter", reflect.TypeOf((*MockGitRepository)(nil).IsNotAfter), ctx, ancestor, child)
}

// PushGovernorSignature mocks base method.
func (m *MockGitRepository) PushGovernorSignature(ctx context.Context, msr *v1alpha1.ManifestSigningRequestManifestObject) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PushGovernorSignature", ctx, msr)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PushGovernorSignature indicates an expected call of PushGovernorSignature.
func (mr *MockGitRepositoryMockRecorder) PushGovernorSignature(ctx, msr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PushGovernorSignature", reflect.TypeOf((*MockGitRepository)(nil).PushGovernorSignature), ctx, msr)
}

// PushMCA mocks base method.
func (m *MockGitRepository) PushMCA(ctx context.Context, msr *v1alpha1.ManifestChangeApprovalManifestObject) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PushMCA", ctx, msr)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PushMCA indicates an expected call of PushMCA.
func (mr *MockGitRepositoryMockRecorder) PushMCA(ctx, msr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PushMCA", reflect.TypeOf((*MockGitRepository)(nil).PushMCA), ctx, msr)
}

// PushMSR mocks base method.
func (m *MockGitRepository) PushMSR(ctx context.Context, msr *v1alpha1.ManifestSigningRequestManifestObject) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PushMSR", ctx, msr)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PushMSR indicates an expected call of PushMSR.
func (mr *MockGitRepositoryMockRecorder) PushMSR(ctx, msr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PushMSR", reflect.TypeOf((*MockGitRepository)(nil).PushMSR), ctx, msr)
}

// RemoveFromIndexFile mocks base method.
func (m *MockGitRepository) RemoveFromIndexFile(ctx context.Context, operationalFileLocation, governanceIndexAlias string) (string, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveFromIndexFile", ctx, operationalFileLocation, governanceIndexAlias)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// RemoveFromIndexFile indicates an expected call of RemoveFromIndexFile.
func (mr *MockGitRepositoryMockRecorder) RemoveFromIndexFile(ctx, operationalFileLocation, governanceIndexAlias any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveFromIndexFile", reflect.TypeOf((*MockGitRepository)(nil).RemoveFromIndexFile), ctx, operationalFileLocation, governanceIndexAlias)
}

// Sync mocks base method.
func (m *MockGitRepository) Sync(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sync", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Sync indicates an expected call of Sync.
func (mr *MockGitRepositoryMockRecorder) Sync(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sync", reflect.TypeOf((*MockGitRepository)(nil).Sync), ctx)
}
