//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApprovalRule) DeepCopyInto(out *ApprovalRule) {
	*out = *in
	if in.Require != nil {
		in, out := &in.Require, &out.Require
		*out = make([]ApprovalRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApprovalRule.
func (in *ApprovalRule) DeepCopy() *ApprovalRule {
	if in == nil {
		return nil
	}
	out := new(ApprovalRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArgoCDApplication) DeepCopyInto(out *ArgoCDApplication) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArgoCDApplication.
func (in *ArgoCDApplication) DeepCopy() *ArgoCDApplication {
	if in == nil {
		return nil
	}
	out := new(ArgoCDApplication)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Governor) DeepCopyInto(out *Governor) {
	*out = *in
	in.NotificationChannel.DeepCopyInto(&out.NotificationChannel)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Governor.
func (in *Governor) DeepCopy() *Governor {
	if in == nil {
		return nil
	}
	out := new(Governor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GovernorList) DeepCopyInto(out *GovernorList) {
	*out = *in
	if in.NotificationChannels != nil {
		in, out := &in.NotificationChannels, &out.NotificationChannels
		*out = make([]NotificationChannel, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Members != nil {
		in, out := &in.Members, &out.Members
		*out = make([]Governor, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GovernorList.
func (in *GovernorList) DeepCopy() *GovernorList {
	if in == nil {
		return nil
	}
	out := new(GovernorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Location) DeepCopyInto(out *Location) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Location.
func (in *Location) DeepCopy() *Location {
	if in == nil {
		return nil
	}
	out := new(Location)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCA) DeepCopyInto(out *MCA) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCA.
func (in *MCA) DeepCopy() *MCA {
	if in == nil {
		return nil
	}
	out := new(MCA)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MSR) DeepCopyInto(out *MSR) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MSR.
func (in *MSR) DeepCopy() *MSR {
	if in == nil {
		return nil
	}
	out := new(MSR)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManifestRequestTemplate) DeepCopyInto(out *ManifestRequestTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManifestRequestTemplate.
func (in *ManifestRequestTemplate) DeepCopy() *ManifestRequestTemplate {
	if in == nil {
		return nil
	}
	out := new(ManifestRequestTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ManifestRequestTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManifestRequestTemplateList) DeepCopyInto(out *ManifestRequestTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ManifestRequestTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManifestRequestTemplateList.
func (in *ManifestRequestTemplateList) DeepCopy() *ManifestRequestTemplateList {
	if in == nil {
		return nil
	}
	out := new(ManifestRequestTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ManifestRequestTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManifestRequestTemplateSpec) DeepCopyInto(out *ManifestRequestTemplateSpec) {
	*out = *in
	out.ArgoCDApplication = in.ArgoCDApplication
	out.Location = in.Location
	out.MSR = in.MSR
	out.MCA = in.MCA
	if in.Governors != nil {
		in, out := &in.Governors, &out.Governors
		*out = make([]Governor, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Require.DeepCopyInto(&out.Require)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManifestRequestTemplateSpec.
func (in *ManifestRequestTemplateSpec) DeepCopy() *ManifestRequestTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(ManifestRequestTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManifestRequestTemplateStatus) DeepCopyInto(out *ManifestRequestTemplateStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManifestRequestTemplateStatus.
func (in *ManifestRequestTemplateStatus) DeepCopy() *ManifestRequestTemplateStatus {
	if in == nil {
		return nil
	}
	out := new(ManifestRequestTemplateStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotificationChannel) DeepCopyInto(out *NotificationChannel) {
	*out = *in
	if in.Slack != nil {
		in, out := &in.Slack, &out.Slack
		*out = new(SlackChannel)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotificationChannel.
func (in *NotificationChannel) DeepCopy() *NotificationChannel {
	if in == nil {
		return nil
	}
	out := new(NotificationChannel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlackChannel) DeepCopyInto(out *SlackChannel) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlackChannel.
func (in *SlackChannel) DeepCopy() *SlackChannel {
	if in == nil {
		return nil
	}
	out := new(SlackChannel)
	in.DeepCopyInto(out)
	return out
}
