//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApprovalRule) DeepCopyInto(out *ApprovalRule) {
	*out = *in
	if in.AtLeast != nil {
		in, out := &in.AtLeast, &out.AtLeast
		*out = new(int)
		**out = **in
	}
	if in.All != nil {
		in, out := &in.All, &out.All
		*out = new(bool)
		**out = **in
	}
	if in.Require != nil {
		in, out := &in.Require, &out.Require
		*out = make([]ApprovalRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApprovalRule.
func (in *ApprovalRule) DeepCopy() *ApprovalRule {
	if in == nil {
		return nil
	}
	out := new(ApprovalRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApproverList) DeepCopyInto(out *ApproverList) {
	*out = *in
	if in.Members != nil {
		in, out := &in.Members, &out.Members
		*out = make([]Governor, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApproverList.
func (in *ApproverList) DeepCopy() *ApproverList {
	if in == nil {
		return nil
	}
	out := new(ApproverList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArgoCDApplication) DeepCopyInto(out *ArgoCDApplication) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArgoCDApplication.
func (in *ArgoCDApplication) DeepCopy() *ArgoCDApplication {
	if in == nil {
		return nil
	}
	out := new(ArgoCDApplication)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FileChange) DeepCopyInto(out *FileChange) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FileChange.
func (in *FileChange) DeepCopy() *FileChange {
	if in == nil {
		return nil
	}
	out := new(FileChange)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitRepository) DeepCopyInto(out *GitRepository) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitRepository.
func (in *GitRepository) DeepCopy() *GitRepository {
	if in == nil {
		return nil
	}
	out := new(GitRepository)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Governor) DeepCopyInto(out *Governor) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Governor.
func (in *Governor) DeepCopy() *Governor {
	if in == nil {
		return nil
	}
	out := new(Governor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GovernorList) DeepCopyInto(out *GovernorList) {
	*out = *in
	if in.NotificationChannels != nil {
		in, out := &in.NotificationChannels, &out.NotificationChannels
		*out = make([]NotificationChannel, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Members != nil {
		in, out := &in.Members, &out.Members
		*out = make([]Governor, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GovernorList.
func (in *GovernorList) DeepCopy() *GovernorList {
	if in == nil {
		return nil
	}
	out := new(GovernorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Location) DeepCopyInto(out *Location) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Location.
func (in *Location) DeepCopy() *Location {
	if in == nil {
		return nil
	}
	out := new(Location)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCA) DeepCopyInto(out *MCA) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCA.
func (in *MCA) DeepCopy() *MCA {
	if in == nil {
		return nil
	}
	out := new(MCA)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManifestChangeApproval) DeepCopyInto(out *ManifestChangeApproval) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManifestChangeApproval.
func (in *ManifestChangeApproval) DeepCopy() *ManifestChangeApproval {
	if in == nil {
		return nil
	}
	out := new(ManifestChangeApproval)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ManifestChangeApproval) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManifestChangeApprovalHistoryRecord) DeepCopyInto(out *ManifestChangeApprovalHistoryRecord) {
	*out = *in
	in.Time.DeepCopyInto(&out.Time)
	if in.Changes != nil {
		in, out := &in.Changes, &out.Changes
		*out = make([]FileChange, len(*in))
		copy(*out, *in)
	}
	in.Governors.DeepCopyInto(&out.Governors)
	in.Require.DeepCopyInto(&out.Require)
	in.Approves.DeepCopyInto(&out.Approves)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManifestChangeApprovalHistoryRecord.
func (in *ManifestChangeApprovalHistoryRecord) DeepCopy() *ManifestChangeApprovalHistoryRecord {
	if in == nil {
		return nil
	}
	out := new(ManifestChangeApprovalHistoryRecord)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManifestChangeApprovalList) DeepCopyInto(out *ManifestChangeApprovalList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ManifestChangeApproval, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManifestChangeApprovalList.
func (in *ManifestChangeApprovalList) DeepCopy() *ManifestChangeApprovalList {
	if in == nil {
		return nil
	}
	out := new(ManifestChangeApprovalList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ManifestChangeApprovalList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManifestChangeApprovalManifestObject) DeepCopyInto(out *ManifestChangeApprovalManifestObject) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ObjectMeta = in.ObjectMeta
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManifestChangeApprovalManifestObject.
func (in *ManifestChangeApprovalManifestObject) DeepCopy() *ManifestChangeApprovalManifestObject {
	if in == nil {
		return nil
	}
	out := new(ManifestChangeApprovalManifestObject)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManifestChangeApprovalSpec) DeepCopyInto(out *ManifestChangeApprovalSpec) {
	*out = *in
	out.MRT = in.MRT
	out.MSR = in.MSR
	out.GitRepository = in.GitRepository
	out.Location = in.Location
	if in.Changes != nil {
		in, out := &in.Changes, &out.Changes
		*out = make([]FileChange, len(*in))
		copy(*out, *in)
	}
	in.Governors.DeepCopyInto(&out.Governors)
	in.Require.DeepCopyInto(&out.Require)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManifestChangeApprovalSpec.
func (in *ManifestChangeApprovalSpec) DeepCopy() *ManifestChangeApprovalSpec {
	if in == nil {
		return nil
	}
	out := new(ManifestChangeApprovalSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManifestChangeApprovalStatus) DeepCopyInto(out *ManifestChangeApprovalStatus) {
	*out = *in
	if in.ApprovalHistory != nil {
		in, out := &in.ApprovalHistory, &out.ApprovalHistory
		*out = make([]ManifestChangeApprovalHistoryRecord, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Approves.DeepCopyInto(&out.Approves)
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManifestChangeApprovalStatus.
func (in *ManifestChangeApprovalStatus) DeepCopy() *ManifestChangeApprovalStatus {
	if in == nil {
		return nil
	}
	out := new(ManifestChangeApprovalStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManifestRef) DeepCopyInto(out *ManifestRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManifestRef.
func (in *ManifestRef) DeepCopy() *ManifestRef {
	if in == nil {
		return nil
	}
	out := new(ManifestRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManifestRefOptional) DeepCopyInto(out *ManifestRefOptional) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManifestRefOptional.
func (in *ManifestRefOptional) DeepCopy() *ManifestRefOptional {
	if in == nil {
		return nil
	}
	out := new(ManifestRefOptional)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManifestRequestTemplate) DeepCopyInto(out *ManifestRequestTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManifestRequestTemplate.
func (in *ManifestRequestTemplate) DeepCopy() *ManifestRequestTemplate {
	if in == nil {
		return nil
	}
	out := new(ManifestRequestTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ManifestRequestTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManifestRequestTemplateList) DeepCopyInto(out *ManifestRequestTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ManifestRequestTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManifestRequestTemplateList.
func (in *ManifestRequestTemplateList) DeepCopy() *ManifestRequestTemplateList {
	if in == nil {
		return nil
	}
	out := new(ManifestRequestTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ManifestRequestTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManifestRequestTemplateSpec) DeepCopyInto(out *ManifestRequestTemplateSpec) {
	*out = *in
	out.GitRepository = in.GitRepository
	if in.PGP != nil {
		in, out := &in.PGP, &out.PGP
		*out = new(PGPPrivateKeySecret)
		**out = **in
	}
	if in.SSH != nil {
		in, out := &in.SSH, &out.SSH
		*out = new(SSHPrivateKeySecret)
		**out = **in
	}
	out.ArgoCDApplication = in.ArgoCDApplication
	out.Location = in.Location
	out.MSR = in.MSR
	out.MCA = in.MCA
	in.Governors.DeepCopyInto(&out.Governors)
	in.Require.DeepCopyInto(&out.Require)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManifestRequestTemplateSpec.
func (in *ManifestRequestTemplateSpec) DeepCopy() *ManifestRequestTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(ManifestRequestTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManifestRequestTemplateStatus) DeepCopyInto(out *ManifestRequestTemplateStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RevisionsQueue != nil {
		in, out := &in.RevisionsQueue, &out.RevisionsQueue
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManifestRequestTemplateStatus.
func (in *ManifestRequestTemplateStatus) DeepCopy() *ManifestRequestTemplateStatus {
	if in == nil {
		return nil
	}
	out := new(ManifestRequestTemplateStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManifestSigningRequest) DeepCopyInto(out *ManifestSigningRequest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManifestSigningRequest.
func (in *ManifestSigningRequest) DeepCopy() *ManifestSigningRequest {
	if in == nil {
		return nil
	}
	out := new(ManifestSigningRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ManifestSigningRequest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManifestSigningRequestHistoryRecord) DeepCopyInto(out *ManifestSigningRequestHistoryRecord) {
	*out = *in
	if in.Changes != nil {
		in, out := &in.Changes, &out.Changes
		*out = make([]FileChange, len(*in))
		copy(*out, *in)
	}
	in.Governors.DeepCopyInto(&out.Governors)
	in.Require.DeepCopyInto(&out.Require)
	in.Approves.DeepCopyInto(&out.Approves)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManifestSigningRequestHistoryRecord.
func (in *ManifestSigningRequestHistoryRecord) DeepCopy() *ManifestSigningRequestHistoryRecord {
	if in == nil {
		return nil
	}
	out := new(ManifestSigningRequestHistoryRecord)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManifestSigningRequestList) DeepCopyInto(out *ManifestSigningRequestList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ManifestSigningRequest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManifestSigningRequestList.
func (in *ManifestSigningRequestList) DeepCopy() *ManifestSigningRequestList {
	if in == nil {
		return nil
	}
	out := new(ManifestSigningRequestList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ManifestSigningRequestList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManifestSigningRequestManifestObject) DeepCopyInto(out *ManifestSigningRequestManifestObject) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ObjectMeta = in.ObjectMeta
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManifestSigningRequestManifestObject.
func (in *ManifestSigningRequestManifestObject) DeepCopy() *ManifestSigningRequestManifestObject {
	if in == nil {
		return nil
	}
	out := new(ManifestSigningRequestManifestObject)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManifestSigningRequestSpec) DeepCopyInto(out *ManifestSigningRequestSpec) {
	*out = *in
	out.MRT = in.MRT
	out.GitRepository = in.GitRepository
	out.Location = in.Location
	if in.Changes != nil {
		in, out := &in.Changes, &out.Changes
		*out = make([]FileChange, len(*in))
		copy(*out, *in)
	}
	in.Governors.DeepCopyInto(&out.Governors)
	in.Require.DeepCopyInto(&out.Require)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManifestSigningRequestSpec.
func (in *ManifestSigningRequestSpec) DeepCopy() *ManifestSigningRequestSpec {
	if in == nil {
		return nil
	}
	out := new(ManifestSigningRequestSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManifestSigningRequestStatus) DeepCopyInto(out *ManifestSigningRequestStatus) {
	*out = *in
	if in.RequestHistory != nil {
		in, out := &in.RequestHistory, &out.RequestHistory
		*out = make([]ManifestSigningRequestHistoryRecord, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Approves.DeepCopyInto(&out.Approves)
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManifestSigningRequestStatus.
func (in *ManifestSigningRequestStatus) DeepCopy() *ManifestSigningRequestStatus {
	if in == nil {
		return nil
	}
	out := new(ManifestSigningRequestStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotificationChannel) DeepCopyInto(out *NotificationChannel) {
	*out = *in
	if in.Slack != nil {
		in, out := &in.Slack, &out.Slack
		*out = new(SlackChannel)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotificationChannel.
func (in *NotificationChannel) DeepCopy() *NotificationChannel {
	if in == nil {
		return nil
	}
	out := new(NotificationChannel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PGPPrivateKeySecret) DeepCopyInto(out *PGPPrivateKeySecret) {
	*out = *in
	out.SecretsRef = in.SecretsRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PGPPrivateKeySecret.
func (in *PGPPrivateKeySecret) DeepCopy() *PGPPrivateKeySecret {
	if in == nil {
		return nil
	}
	out := new(PGPPrivateKeySecret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QubmangoIndex) DeepCopyInto(out *QubmangoIndex) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QubmangoIndex.
func (in *QubmangoIndex) DeepCopy() *QubmangoIndex {
	if in == nil {
		return nil
	}
	out := new(QubmangoIndex)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *QubmangoIndex) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QubmangoIndexList) DeepCopyInto(out *QubmangoIndexList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]QubmangoIndex, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QubmangoIndexList.
func (in *QubmangoIndexList) DeepCopy() *QubmangoIndexList {
	if in == nil {
		return nil
	}
	out := new(QubmangoIndexList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *QubmangoIndexList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QubmangoIndexSpec) DeepCopyInto(out *QubmangoIndexSpec) {
	*out = *in
	if in.Policies != nil {
		in, out := &in.Policies, &out.Policies
		*out = make([]QubmangoPolicy, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QubmangoIndexSpec.
func (in *QubmangoIndexSpec) DeepCopy() *QubmangoIndexSpec {
	if in == nil {
		return nil
	}
	out := new(QubmangoIndexSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QubmangoIndexStatus) DeepCopyInto(out *QubmangoIndexStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QubmangoIndexStatus.
func (in *QubmangoIndexStatus) DeepCopy() *QubmangoIndexStatus {
	if in == nil {
		return nil
	}
	out := new(QubmangoIndexStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QubmangoPolicy) DeepCopyInto(out *QubmangoPolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QubmangoPolicy.
func (in *QubmangoPolicy) DeepCopy() *QubmangoPolicy {
	if in == nil {
		return nil
	}
	out := new(QubmangoPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SSHPrivateKeySecret) DeepCopyInto(out *SSHPrivateKeySecret) {
	*out = *in
	out.SecretsRef = in.SecretsRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SSHPrivateKeySecret.
func (in *SSHPrivateKeySecret) DeepCopy() *SSHPrivateKeySecret {
	if in == nil {
		return nil
	}
	out := new(SSHPrivateKeySecret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlackChannel) DeepCopyInto(out *SlackChannel) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlackChannel.
func (in *SlackChannel) DeepCopy() *SlackChannel {
	if in == nil {
		return nil
	}
	out := new(SlackChannel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VersionedManifestRef) DeepCopyInto(out *VersionedManifestRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VersionedManifestRef.
func (in *VersionedManifestRef) DeepCopy() *VersionedManifestRef {
	if in == nil {
		return nil
	}
	out := new(VersionedManifestRef)
	in.DeepCopyInto(out)
	return out
}
