// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/manager.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/manager.go -destination=internal/repository/mocks/manager_mock.go -package=manager_mock
//

// Package manager_mock is a generated GoMock package.
package manager_mock

import (
	context "context"
	reflect "reflect"

	crypto "github.com/AlwaysSayNo/quorum-based-manifests-governance/cli/internal/crypto"
	repository "github.com/AlwaysSayNo/quorum-based-manifests-governance/cli/internal/repository"
	transport "github.com/go-git/go-git/v5/plumbing/transport"
	gomock "go.uber.org/mock/gomock"
)

// MockGitRepositoryFactory is a mock of GitRepositoryFactory interface.
type MockGitRepositoryFactory struct {
	ctrl     *gomock.Controller
	recorder *MockGitRepositoryFactoryMockRecorder
	isgomock struct{}
}

// MockGitRepositoryFactoryMockRecorder is the mock recorder for MockGitRepositoryFactory.
type MockGitRepositoryFactoryMockRecorder struct {
	mock *MockGitRepositoryFactory
}

// NewMockGitRepositoryFactory creates a new mock instance.
func NewMockGitRepositoryFactory(ctrl *gomock.Controller) *MockGitRepositoryFactory {
	mock := &MockGitRepositoryFactory{ctrl: ctrl}
	mock.recorder = &MockGitRepositoryFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGitRepositoryFactory) EXPECT() *MockGitRepositoryFactoryMockRecorder {
	return m.recorder
}

// IdentifyProvider mocks base method.
func (m *MockGitRepositoryFactory) IdentifyProvider(repoURL string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IdentifyProvider", repoURL)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IdentifyProvider indicates an expected call of IdentifyProvider.
func (mr *MockGitRepositoryFactoryMockRecorder) IdentifyProvider(repoURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IdentifyProvider", reflect.TypeOf((*MockGitRepositoryFactory)(nil).IdentifyProvider), repoURL)
}

// New mocks base method.
func (m *MockGitRepositoryFactory) New(ctx context.Context, remoteURL, localPath string, auth transport.AuthMethod, pgpSecrets crypto.Secrets) (repository.GitRepositoryProvider, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "New", ctx, remoteURL, localPath, auth, pgpSecrets)
	ret0, _ := ret[0].(repository.GitRepositoryProvider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// New indicates an expected call of New.
func (mr *MockGitRepositoryFactoryMockRecorder) New(ctx, remoteURL, localPath, auth, pgpSecrets any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "New", reflect.TypeOf((*MockGitRepositoryFactory)(nil).New), ctx, remoteURL, localPath, auth, pgpSecrets)
}

// MockGitRepositoryProvider is a mock of GitRepositoryProvider interface.
type MockGitRepositoryProvider struct {
	ctrl     *gomock.Controller
	recorder *MockGitRepositoryProviderMockRecorder
	isgomock struct{}
}

// MockGitRepositoryProviderMockRecorder is the mock recorder for MockGitRepositoryProvider.
type MockGitRepositoryProviderMockRecorder struct {
	mock *MockGitRepositoryProvider
}

// NewMockGitRepositoryProvider creates a new mock instance.
func NewMockGitRepositoryProvider(ctrl *gomock.Controller) *MockGitRepositoryProvider {
	mock := &MockGitRepositoryProvider{ctrl: ctrl}
	mock.recorder = &MockGitRepositoryProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGitRepositoryProvider) EXPECT() *MockGitRepositoryProviderMockRecorder {
	return m.recorder
}

// GetActiveMSR mocks base method.
func (m *MockGitRepositoryProvider) GetActiveMSR(ctx context.Context, policy *repository.QubmangoPolicy) (*repository.ManifestSigningRequestManifestObject, []byte, repository.SignatureData, []repository.SignatureData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveMSR", ctx, policy)
	ret0, _ := ret[0].(*repository.ManifestSigningRequestManifestObject)
	ret1, _ := ret[1].([]byte)
	ret2, _ := ret[2].(repository.SignatureData)
	ret3, _ := ret[3].([]repository.SignatureData)
	ret4, _ := ret[4].(error)
	return ret0, ret1, ret2, ret3, ret4
}

// GetActiveMSR indicates an expected call of GetActiveMSR.
func (mr *MockGitRepositoryProviderMockRecorder) GetActiveMSR(ctx, policy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveMSR", reflect.TypeOf((*MockGitRepositoryProvider)(nil).GetActiveMSR), ctx, policy)
}

// GetChangedFilesRaw mocks base method.
func (m *MockGitRepositoryProvider) GetChangedFilesRaw(ctx context.Context, fromCommit, toCommit, fromFolder string) (map[string]repository.FileBytesWithStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChangedFilesRaw", ctx, fromCommit, toCommit, fromFolder)
	ret0, _ := ret[0].(map[string]repository.FileBytesWithStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChangedFilesRaw indicates an expected call of GetChangedFilesRaw.
func (mr *MockGitRepositoryProviderMockRecorder) GetChangedFilesRaw(ctx, fromCommit, toCommit, fromFolder any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChangedFilesRaw", reflect.TypeOf((*MockGitRepositoryProvider)(nil).GetChangedFilesRaw), ctx, fromCommit, toCommit, fromFolder)
}

// GetLatestRevision mocks base method.
func (m *MockGitRepositoryProvider) GetLatestRevision(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestRevision", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestRevision indicates an expected call of GetLatestRevision.
func (mr *MockGitRepositoryProviderMockRecorder) GetLatestRevision(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestRevision", reflect.TypeOf((*MockGitRepositoryProvider)(nil).GetLatestRevision), ctx)
}

// GetQubmangoIndex mocks base method.
func (m *MockGitRepositoryProvider) GetQubmangoIndex(ctx context.Context) (*repository.QubmangoIndex, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQubmangoIndex", ctx)
	ret0, _ := ret[0].(*repository.QubmangoIndex)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetQubmangoIndex indicates an expected call of GetQubmangoIndex.
func (mr *MockGitRepositoryProviderMockRecorder) GetQubmangoIndex(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQubmangoIndex", reflect.TypeOf((*MockGitRepositoryProvider)(nil).GetQubmangoIndex), ctx)
}

// HasRevision mocks base method.
func (m *MockGitRepositoryProvider) HasRevision(ctx context.Context, commit string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasRevision", ctx, commit)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasRevision indicates an expected call of HasRevision.
func (mr *MockGitRepositoryProviderMockRecorder) HasRevision(ctx, commit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasRevision", reflect.TypeOf((*MockGitRepositoryProvider)(nil).HasRevision), ctx, commit)
}

// PushSignature mocks base method.
func (m *MockGitRepositoryProvider) PushSignature(ctx context.Context, msr *repository.ManifestSigningRequestManifestObject, signatureData repository.SignatureData) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PushSignature", ctx, msr, signatureData)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PushSignature indicates an expected call of PushSignature.
func (mr *MockGitRepositoryProviderMockRecorder) PushSignature(ctx, msr, signatureData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PushSignature", reflect.TypeOf((*MockGitRepositoryProvider)(nil).PushSignature), ctx, msr, signatureData)
}

// Sync mocks base method.
func (m *MockGitRepositoryProvider) Sync(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sync", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Sync indicates an expected call of Sync.
func (mr *MockGitRepositoryProviderMockRecorder) Sync(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sync", reflect.TypeOf((*MockGitRepositoryProvider)(nil).Sync), ctx)
}
