// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/manager.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/manager.go -destination=internal/repository/mocks/manager_mock.go -package=manager_mock
//

// Package manager_mock is a generated GoMock package.
package manager_mock

import (
	context "context"
	reflect "reflect"

	config "github.com/AlwaysSayNo/quorum-based-manifests-governance/cli/internal/config"
	crypto "github.com/AlwaysSayNo/quorum-based-manifests-governance/cli/internal/crypto"
	repository "github.com/AlwaysSayNo/quorum-based-manifests-governance/cli/internal/repository"
	dto "github.com/AlwaysSayNo/quorum-based-manifests-governance/pkg/api/dto"
	diff "github.com/go-git/go-git/v5/plumbing/format/diff"
	transport "github.com/go-git/go-git/v5/plumbing/transport"
	gomock "go.uber.org/mock/gomock"
)

// MockGitRepositoryFactory is a mock of GitRepositoryFactory interface.
type MockGitRepositoryFactory struct {
	ctrl     *gomock.Controller
	recorder *MockGitRepositoryFactoryMockRecorder
	isgomock struct{}
}

// MockGitRepositoryFactoryMockRecorder is the mock recorder for MockGitRepositoryFactory.
type MockGitRepositoryFactoryMockRecorder struct {
	mock *MockGitRepositoryFactory
}

// NewMockGitRepositoryFactory creates a new mock instance.
func NewMockGitRepositoryFactory(ctrl *gomock.Controller) *MockGitRepositoryFactory {
	mock := &MockGitRepositoryFactory{ctrl: ctrl}
	mock.recorder = &MockGitRepositoryFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGitRepositoryFactory) EXPECT() *MockGitRepositoryFactoryMockRecorder {
	return m.recorder
}

// IdentifyProvider mocks base method.
func (m *MockGitRepositoryFactory) IdentifyProvider(repoURL string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IdentifyProvider", repoURL)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IdentifyProvider indicates an expected call of IdentifyProvider.
func (mr *MockGitRepositoryFactoryMockRecorder) IdentifyProvider(repoURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IdentifyProvider", reflect.TypeOf((*MockGitRepositoryFactory)(nil).IdentifyProvider), repoURL)
}

// New mocks base method.
func (m *MockGitRepositoryFactory) New(ctx context.Context, remoteURL, localPath string, auth transport.AuthMethod, pgpSecrets crypto.Secrets) (repository.GitRepositoryProvider, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "New", ctx, remoteURL, localPath, auth, pgpSecrets)
	ret0, _ := ret[0].(repository.GitRepositoryProvider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// New indicates an expected call of New.
func (mr *MockGitRepositoryFactoryMockRecorder) New(ctx, remoteURL, localPath, auth, pgpSecrets any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "New", reflect.TypeOf((*MockGitRepositoryFactory)(nil).New), ctx, remoteURL, localPath, auth, pgpSecrets)
}

// MockGitRepositoryProvider is a mock of GitRepositoryProvider interface.
type MockGitRepositoryProvider struct {
	ctrl     *gomock.Controller
	recorder *MockGitRepositoryProviderMockRecorder
	isgomock struct{}
}

// MockGitRepositoryProviderMockRecorder is the mock recorder for MockGitRepositoryProvider.
type MockGitRepositoryProviderMockRecorder struct {
	mock *MockGitRepositoryProvider
}

// NewMockGitRepositoryProvider creates a new mock instance.
func NewMockGitRepositoryProvider(ctrl *gomock.Controller) *MockGitRepositoryProvider {
	mock := &MockGitRepositoryProvider{ctrl: ctrl}
	mock.recorder = &MockGitRepositoryProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGitRepositoryProvider) EXPECT() *MockGitRepositoryProviderMockRecorder {
	return m.recorder
}

// GetChangedFilesRaw mocks base method.
func (m *MockGitRepositoryProvider) GetChangedFilesRaw(ctx context.Context, fromCommit, toCommit, fromFolder string) (map[string]dto.FileBytesWithStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChangedFilesRaw", ctx, fromCommit, toCommit, fromFolder)
	ret0, _ := ret[0].(map[string]dto.FileBytesWithStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChangedFilesRaw indicates an expected call of GetChangedFilesRaw.
func (mr *MockGitRepositoryProviderMockRecorder) GetChangedFilesRaw(ctx, fromCommit, toCommit, fromFolder any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChangedFilesRaw", reflect.TypeOf((*MockGitRepositoryProvider)(nil).GetChangedFilesRaw), ctx, fromCommit, toCommit, fromFolder)
}

// GetFileDiffPatchParts mocks base method.
func (m *MockGitRepositoryProvider) GetFileDiffPatchParts(ctx context.Context, msr *dto.ManifestSigningRequestManifestObject, fromCommit, toCommit string) (map[string]diff.Patch, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFileDiffPatchParts", ctx, msr, fromCommit, toCommit)
	ret0, _ := ret[0].(map[string]diff.Patch)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFileDiffPatchParts indicates an expected call of GetFileDiffPatchParts.
func (mr *MockGitRepositoryProviderMockRecorder) GetFileDiffPatchParts(ctx, msr, fromCommit, toCommit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFileDiffPatchParts", reflect.TypeOf((*MockGitRepositoryProvider)(nil).GetFileDiffPatchParts), ctx, msr, fromCommit, toCommit)
}

// GetLatestMSR mocks base method.
func (m *MockGitRepositoryProvider) GetLatestMSR(ctx context.Context, policy *repository.GovernancePolicy) (*repository.MSRInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestMSR", ctx, policy)
	ret0, _ := ret[0].(*repository.MSRInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestMSR indicates an expected call of GetLatestMSR.
func (mr *MockGitRepositoryProviderMockRecorder) GetLatestMSR(ctx, policy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestMSR", reflect.TypeOf((*MockGitRepositoryProvider)(nil).GetLatestMSR), ctx, policy)
}

// GetLatestRevision mocks base method.
func (m *MockGitRepositoryProvider) GetLatestRevision(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestRevision", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestRevision indicates an expected call of GetLatestRevision.
func (mr *MockGitRepositoryProviderMockRecorder) GetLatestRevision(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestRevision", reflect.TypeOf((*MockGitRepositoryProvider)(nil).GetLatestRevision), ctx)
}

// GetMCAHistory mocks base method.
func (m *MockGitRepositoryProvider) GetMCAHistory(ctx context.Context, policy *repository.GovernancePolicy) ([]repository.MCAInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMCAHistory", ctx, policy)
	ret0, _ := ret[0].([]repository.MCAInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMCAHistory indicates an expected call of GetMCAHistory.
func (mr *MockGitRepositoryProviderMockRecorder) GetMCAHistory(ctx, policy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMCAHistory", reflect.TypeOf((*MockGitRepositoryProvider)(nil).GetMCAHistory), ctx, policy)
}

// HasRevision mocks base method.
func (m *MockGitRepositoryProvider) HasRevision(ctx context.Context, commit string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasRevision", ctx, commit)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasRevision indicates an expected call of HasRevision.
func (mr *MockGitRepositoryProviderMockRecorder) HasRevision(ctx, commit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasRevision", reflect.TypeOf((*MockGitRepositoryProvider)(nil).HasRevision), ctx, commit)
}

// PushGovernorSignature mocks base method.
func (m *MockGitRepositoryProvider) PushGovernorSignature(ctx context.Context, msr *dto.ManifestSigningRequestManifestObject, user config.UserInfo) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PushGovernorSignature", ctx, msr, user)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PushGovernorSignature indicates an expected call of PushGovernorSignature.
func (mr *MockGitRepositoryProviderMockRecorder) PushGovernorSignature(ctx, msr, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PushGovernorSignature", reflect.TypeOf((*MockGitRepositoryProvider)(nil).PushGovernorSignature), ctx, msr, user)
}

// Sync mocks base method.
func (m *MockGitRepositoryProvider) Sync(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sync", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Sync indicates an expected call of Sync.
func (mr *MockGitRepositoryProviderMockRecorder) Sync(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sync", reflect.TypeOf((*MockGitRepositoryProvider)(nil).Sync), ctx)
}
