apiVersion: manifestrequesttemplates.governance/v1alpha1
kind: ManifestRequestTemplate

# MRTs are created by cluster administrators to define
# the configuration for Quorum Based Manifests Governance
# for their clusters.

metadata:
  name: mrt-sample
  namespace: ns1
  # Each MRT must specify a version number.
  # The creation of governance resource will fail if the version is not specified
  # or lower/equal to an existing version.
  # It only changes, when new MRT is created and approved by the governors,
  # following the previous version rules.
  version: 1

spec:
  # Public key can be specified either inline
  # or by reference (might be implemented later) to a Secret.
  publicKeyRef:
    name: public-key-sample
    namespace: ns1
  publicKey: |
    -----

  argoCDApplication:
    name: argocd-sample-app
    namespace: argocd

  location:
    # Folder where MSR, MCA and Signatures will be stored.
    # Optional. Default: root of the repo.
    folder: "infrastructure/manifest-signing-requests/"

  msr:
    # Default name is msr
    name: msr-sample
    # Default namespace where MRT is created.
    namespace: ns1
  
  mca:
    # Default name is mca
    name: mca-sample
    # Default namespace where MRT is created.
    namespace: ns1


  # Governors can be specified either in MSR or by reference (might be implemented later).
  governorsRef:
    name: governors-sample
    namespace: ns1
  governors:
    notificationChannels:
      - slack:
          groupID: C87654321
    members:
      - alias: voter1
        publicKey: |
          -----
        notificationChannel:
          slack:
            userGroupID: C12345678
      - alias: voter2
        publicKey: |
          -----
      # - ... more governors

  require:
    all: true
    require:
      - signer: $owner
      - atLeast: 2
        require:
          - signer: $voter1
          - signer: $voter2
          # - ... more governors
