apiVersion: manifestsigningrequest.governance/v1alpha1
kind: ManifestSigningRequest

# MSRs are created by MSR controller
# on receiving an event from MRT controller,
# when manifests are created/updated/deleted in the target repository.

metadata:
  name: msr-sample
  namespace: ns1
  # Each MSR must specify a version number.
  # This version must be always higher than previous MSR version.
  version: 22

# Spec is created based on information from the MRT
spec:
  previousApprovedMsr:
    name: msr-sample
    namespace: ns1
    version: 18
    sha256: abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890

  gitRepository:
    url: "https://github.com/example/repo"
    branch: main
    # By default it's msrFolder/v_*/signatures/ if not specified otherwise in MRT.
    # Logic to specify custom signatureFolder is not implemented yet.
    signatureFolder: "infrastructure/manifest-signing-requests/v_22/signatures/"
  
  manifests:
    - name: deployment.yml
      folder: "infrastructure/cluster-a/"
      kind: Deployment
      sha256: abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890
      # maybe status of the file new/updated/deleted
    - name: service.yml
      folder: "infrastructure/cluster-b/"
      kind: Service
      sha256: 1234567890abcdef1234567890abcdef1234567890
    # ... more changed manifests

  require:
    all: true
    require:
      - signer: $owner
      - atLeast: 2
        require:
          - signer: $voter1
          - signer: $voter2
          # - ... more governors
    
    