// Code generated by MockGen. DO NOT EDIT.
// Source: internal/notifier/notifier.go
//
// Generated by this command:
//
//	mockgen -source=internal/notifier/notifier.go -destination=internal/notifier/mocks/notifier_mock.go -package=notifier_mock
//

// Package notifier_mock is a generated GoMock package.
package notifier_mock

import (
	context "context"
	reflect "reflect"

	v1alpha1 "github.com/AlwaysSayNo/quorum-based-manifests-governance/kubernetes/api/v1alpha1"
	notifier "github.com/AlwaysSayNo/quorum-based-manifests-governance/kubernetes/internal/notifier"
	gomock "go.uber.org/mock/gomock"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// MockNotifier is a mock of Notifier interface.
type MockNotifier struct {
	ctrl     *gomock.Controller
	recorder *MockNotifierMockRecorder
	isgomock struct{}
}

// MockNotifierMockRecorder is the mock recorder for MockNotifier.
type MockNotifierMockRecorder struct {
	mock *MockNotifier
}

// NewMockNotifier creates a new mock instance.
func NewMockNotifier(ctrl *gomock.Controller) *MockNotifier {
	mock := &MockNotifier{ctrl: ctrl}
	mock.recorder = &MockNotifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotifier) EXPECT() *MockNotifierMockRecorder {
	return m.recorder
}

// NotifyError mocks base method.
func (m *MockNotifier) NotifyError(ctx context.Context, channels []v1alpha1.NotificationChannel, message string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NotifyError", ctx, channels, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// NotifyError indicates an expected call of NotifyError.
func (mr *MockNotifierMockRecorder) NotifyError(ctx, channels, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyError", reflect.TypeOf((*MockNotifier)(nil).NotifyError), ctx, channels, message)
}

// NotifyGovernorsMCA mocks base method.
func (m *MockNotifier) NotifyGovernorsMCA(ctx context.Context, mca *v1alpha1.ManifestChangeApproval) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NotifyGovernorsMCA", ctx, mca)
	ret0, _ := ret[0].(error)
	return ret0
}

// NotifyGovernorsMCA indicates an expected call of NotifyGovernorsMCA.
func (mr *MockNotifierMockRecorder) NotifyGovernorsMCA(ctx, mca any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyGovernorsMCA", reflect.TypeOf((*MockNotifier)(nil).NotifyGovernorsMCA), ctx, mca)
}

// NotifyGovernorsMSR mocks base method.
func (m *MockNotifier) NotifyGovernorsMSR(ctx context.Context, msr *v1alpha1.ManifestSigningRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NotifyGovernorsMSR", ctx, msr)
	ret0, _ := ret[0].(error)
	return ret0
}

// NotifyGovernorsMSR indicates an expected call of NotifyGovernorsMSR.
func (mr *MockNotifierMockRecorder) NotifyGovernorsMSR(ctx, msr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyGovernorsMSR", reflect.TypeOf((*MockNotifier)(nil).NotifyGovernorsMSR), ctx, msr)
}

// SupportsChannel mocks base method.
func (m *MockNotifier) SupportsChannel(channels []v1alpha1.NotificationChannel) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SupportsChannel", channels)
	ret0, _ := ret[0].(bool)
	return ret0
}

// SupportsChannel indicates an expected call of SupportsChannel.
func (mr *MockNotifierMockRecorder) SupportsChannel(channels any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SupportsChannel", reflect.TypeOf((*MockNotifier)(nil).SupportsChannel), channels)
}

// MockNotifierFactory is a mock of NotifierFactory interface.
type MockNotifierFactory struct {
	ctrl     *gomock.Controller
	recorder *MockNotifierFactoryMockRecorder
	isgomock struct{}
}

// MockNotifierFactoryMockRecorder is the mock recorder for MockNotifierFactory.
type MockNotifierFactoryMockRecorder struct {
	mock *MockNotifierFactory
}

// NewMockNotifierFactory creates a new mock instance.
func NewMockNotifierFactory(ctrl *gomock.Controller) *MockNotifierFactory {
	mock := &MockNotifierFactory{ctrl: ctrl}
	mock.recorder = &MockNotifierFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotifierFactory) EXPECT() *MockNotifierFactoryMockRecorder {
	return m.recorder
}

// New mocks base method.
func (m *MockNotifierFactory) New(k8sClient client.Client) notifier.Notifier {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "New", k8sClient)
	ret0, _ := ret[0].(notifier.Notifier)
	return ret0
}

// New indicates an expected call of New.
func (mr *MockNotifierFactoryMockRecorder) New(k8sClient any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "New", reflect.TypeOf((*MockNotifierFactory)(nil).New), k8sClient)
}
